apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask-app-conf
  name: flask-app-conf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-conf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask-app-conf
    spec:
      containers:
      - image: alishersa1233/flask-app
        name: flask-app
        env:
        - name: CPU
          valueFrom:
            resourceFieldRef:
              containerName: flask-app-conf
              resource: requests.cpu
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MEMORY
          valueFrom:
            resourceFieldRef:
              containerName: flask-app-conf
              resource: requests.memory
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: environment
              key: LOG_LEVEL
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: database
              key: DB_URI
        resources:
          requests:
            memory: "100Mi"
            cpu: "64m"
          limits:
            memory: "200Mi"
            cpu: "128m"

