apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask-app-conf
  name: flask-app-conf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-conf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask-app-conf
    spec:
      containers:
      - image: alishersa1233/flask-app
        name: flask-app
        resources: {}
status: {}
